<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */
 
 class eventclass_app_logs  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["BeforeProcessList"]=true;

		$this->events["BeforeProcessAdd"]=true;


	}

//	handlers

				// List page: Before process
function BeforeProcessList(&$pageObject)
{

		
/*

if(strftime("%H:%M:%S")>="15:00:00"||$_SERVER["REMOTE_ADDR"]!="::1"){
// Place event code here.
// Use "Add Action" button to add code snippets.
$message="this is NOT the time to enter into the app please wait for tomorrow";
session_destroy();
}

*/
// Place event code here.
// Use "Add Action" button to add code snippets.
;		
} // function BeforeProcessList

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
				// Add page: Before process
function BeforeProcessAdd(&$pageObject)
{

		

/*

if(strftime("%H:%M:%S")>="15:00:00"||$_SERVER["REMOTE_ADDR"]!="::1"){
// Place event code here.
// Use "Add Action" button to add code snippets.
$message="this is NOT the time to enter into the app please wait for tomorrow";
session_destroy();
}


*/
// Place event code here.
// Use "Add Action" button to add code snippets.
;		
} // function BeforeProcessAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>
