<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */
 
 class eventclass_asset_in_the_store  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["AfterAdd"]=true;

		$this->events["BeforeInsert"]=true;

		$this->events["BeforeProcessList"]=true;

		$this->events["BeforeProcessRowList"]=true;


	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// After record added
function AfterAdd(&$values, &$keys, $inline, &$pageObject)
{

		

//**********  Check if specific record exists  ************

$rs = DB::Query("select * from assetnumber where assetname='".$values['asset_name']."' and model='".$values['asset_model']."'");
$data=$rs->fetchAssoc();
if($data)
{
	// if record exists do something
$rss=DB::Query("select count(*) as total from asset where asset_name='".$values['asset_name']."' and asset_model='".$values['asset_model']."' and taken='no'");
$dd=$rss->fetchAssoc();
$dda=$dd['total'];



$sql = "update assetnumber set total_number='".$dda."' where assetname='".$values['asset_name']."' and model='".$values['asset_model']."'";

CustomQuery($sql);



}
else 
{

	// if dont exist do something else
$id=$values['asset_name'];
$mod=$values['asset_model'];


//**********  Insert a record into another table  ************

$data = array();
$data["assetid"]=$values['asset_id'];
$data["assetname"] = $id;
$data["model"] = $mod;
$data["total_number"]="1";
DB::Insert("assetnumber", $data );




// Place event code here.
// Use "Add Action" button to add code snippets.
}



;		
} // function AfterAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before Insert Record
function BeforeInsert(&$rawvalues, &$values, &$pageObject, &$message)
{

		if(strftime("%H:%M:%S")>="15:00:00"||$_SERVER["REMOTE_ADDR"]!="::1"){
// Place event code here.
// Use "Add Action" button to add code snippets.
$message="this is NOT the time to enter into the app please wait for tomorrow";
session_destroy();
}

//**********  Check if specific record exists  ************

$rs = DB::Query("select * from asset where asset_name='".$rawvalues['asset_name']."'   and asset_model='".$rawvalues['asset_model']."'    and asset_serial='".$rawvalues['asset_serial']);
$data=$rs->fetchAssoc();
if($data)
{
	// if record exists do something
$message="this asset is already recorded";
return false;
}
else
{
	// if dont exist do something else


//**********  Check if specific record exists  ************

$rs = DB::Query("select * from assetnumber where assetname='".$values['asset_name'] ."'  and model='".$values['asset_model']."'");
$data=$rs->fetchAssoc();
if($data)
{
	// if record exists do something
$rs = DB::Query("select count(*) as total from asset where asset_name='".$values['asset_name'] ."'  and asset_model='".$values['asset_model']."' and taken='no'");
$data2=$rs->fetchAssoc();

$sql = "update assetnumber set totalnumber='".$data2['total']."' where assetname='".$values['asset_name']."' model='".$values['asset_model']."'";
$rs = CustomQuery($sql);
$data = db_fetch_array($rs);
return true;




}
else
{
$data = array();
$data["assetname"] =$values['asset_name'];
$data["model"] =$values['asset_model'];
$data["totalnumber"] = '1';
DB::Insert("assetnumber", $data );
return true;
	// if dont exist do something else


//**********  Insert a record into another table  ************






}



}




// Place event code here.
// Use "Add Action" button to add code snippets.

return true;
;		
} // function BeforeInsert

		
		
		
		
		

				// List page: Before process
function BeforeProcessList(&$pageObject)
{

		
/*

if(strftime("%H:%M:%S")>="15:00:00"||$_SERVER["REMOTE_ADDR"]!="::1"){
// Place event code here.
// Use "Add Action" button to add code snippets.
$message="this is NOT the time to enter into the app please wait for tomorrow";
session_destroy();
}


*/
// Place event code here.
// Use "Add Action" button to add code snippets.
;		
} // function BeforeProcessList

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// List page: Before record processed
function BeforeProcessRowList(&$data, &$pageObject)
{

		


// Place event code here.
// Use "Add Action" button to add code snippets.

;		
} // function BeforeProcessRowList

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>
