<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */
 
 class eventclass_checkapproval  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["BeforeProcessRowList"]=true;

		$this->events["BeforeProcessList"]=true;

		$this->events["ProcessValuesAdd"]=true;

		$this->events["BeforeAdd"]=true;

		$this->events["BeforeProcessAdd"]=true;

		$this->events["BeforeProcessEdit"]=true;

		$this->events["BeforeEdit"]=true;


	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// List page: Before record processed
function BeforeProcessRowList(&$data, &$pageObject)
{

		$uname=Security::getUserName();

$s1="select * from csa_users where username='".$data['ictdeptemp']."'";
$r1=CustomQuery($s1);
$d1=db_fetch_array($r1);




$s="select * from csa_users where username='".$uname."'";
$r=CustomQuery($s);
$d=db_fetch_array($r);


$ss="select * from employee where id='".$d['empid']."'";

$rr=CustomQuery($ss);
$dd=db_fetch_array($rr);

if($dd['department']=='15'){

if($d['groupid']=='2' )
{

return true;

}
elseif($d['groupid']=='6'){
return true;
}



}
else
return false;


// Place event code here.
// Use "Add Action" button to add code snippets.


;		
} // function BeforeProcessRowList

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

				// List page: Before process
function BeforeProcessList(&$pageObject)
{

		$uname=Security::getUserName();

$s="select * from csa_users where username='".$uname."'";
$r=CustomQuery($s);
$d=db_fetch_array($r);

$ss="select * from employee where id='".$d['empid']."'";

$rr=CustomQuery($ss);
$dd=db_fetch_array($rr);

if($dd['department']!='15'){

$pageObject->hideItem("add");
 $pageObject->hideItem("delete");


}


// Place event code here.
// Use "Add Action" button to add code snippets.
;		
} // function BeforeProcessList

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Process record values
function ProcessValuesAdd(&$values, &$pageObject)
{

		$uname=Security::getUserName();

$s="select * from csa_users where username='".$uname."'";
$r=CustomQuery($s);
$d=db_fetch_array($r);

$ss="select * from employee where id='".$d['empid']."'";

$rr=CustomQuery($ss);
$dd=db_fetch_array($rr);

if($d['groupid']=='2'){


$pageObject->hideField("ictdeptemp");


}
else{
$pageObject->hideField("ictdeptmanager");
}




// Place event code here.
// Use "Add Action" button to add code snippets.
;		
} // function ProcessValuesAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before record added
function BeforeAdd(&$values, &$message, $inline, &$pageObject)
{

		$uname=Security::getUserName();

$s="select * from csa_users where username='".$uname."'";
$r=CustomQuery($s);
$d=db_fetch_array($r);

// Place event code here.
// Use "Add Action" button to add code snippets.

if($d['groupid']=='2' && $values['ictdeptmanager']==$d['empid']){
return true;
}
elseif($d['groupid']=='6' && $values['ictdeptemp']==$d['empid']){
return true;
}
else{

$message="please choose your own id for signature";
return false;
}

;		
} // function BeforeAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
				// Add page: Before process
function BeforeProcessAdd(&$pageObject)
{

		
$uname=Security::getUserName();

$s="select * from csa_users where username='".$uname."'";
$r=CustomQuery($s);
$d=db_fetch_array($r);

$ss="select * from employee where id='".$d['empid']."'";

$rr=CustomQuery($ss);
$dd=db_fetch_array($rr);

if($d['groupid']=='2'){


$pageObject->hideField("ictdeptemp");


}
else{
$pageObject->hideField("ictdeptmanager");
}
// Place event code here.
// Use "Add Action" button to add code snippets.
;		
} // function BeforeProcessAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
				// Edit page: Before process
function BeforeProcessEdit(&$pageObject)
{

		$uname=Security::getUserName();

$s="select * from csa_users where username='".$uname."'";
$r=CustomQuery($s);
$d=db_fetch_array($r);

$ss="select * from employee where id='".$d['empid']."'";

$rr=CustomQuery($ss);
$dd=db_fetch_array($rr);

if($d['groupid']=='2'){


$pageObject->hideField("ictdeptemp");


}
else{
$pageObject->hideField("ictdeptmanager");
}


// Place event code here.
// Use "Add Action" button to add code snippets.
;		
} // function BeforeProcessEdit

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before record updated
function BeforeEdit(&$values, $where, &$oldvalues, &$keys, &$message, $inline, &$pageObject)
{

		
$uname=Security::getUserName();

$s="select * from csa_users where username='".$uname."'";
$r=CustomQuery($s);
$d=db_fetch_array($r);

// Place event code here.
// Use "Add Action" button to add code snippets.

if($d['groupid']=='2' && $values['ictdeptmanager']==$d['empid']){
return true;
}
elseif($d['groupid']=='6' && $values['ictdeptemp']==$d['empid']){
return true;
}
else{

$message="please choose your own id for signature";
return false;
}


// Place event code here.
// Use "Add Action" button to add code snippets
;		
} // function BeforeEdit

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>
