<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */
 
 class eventclass_employee  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["AfterAdd"]=true;

		$this->events["BeforeInsert"]=true;

		$this->events["BeforeAdd"]=true;

		$this->events["AfterEdit"]=true;

		$this->events["BeforeProcessList"]=true;

		$this->events["BeforeProcessAdd"]=true;

		$this->events["BeforeProcessEdit"]=true;

		$this->events["BeforeProcessImport"]=true;

		$this->events["BeforeProcessRowList"]=true;


	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// After record added
function AfterAdd(&$values, &$keys, $inline, &$pageObject)
{

		

//**********  Insert a record into another table  ************

$data = array();
$data["job_id"] = $values['job_id'];
$data["empid"] = $values['id'];
$data["workunit_id"]=$values['workunit_id'];
$data["start_date"]=$values['hire_date'];
DB::Insert("jobhistory", $data );



//**********  Insert a record into another table  ************

$data1 = array();
$data1["username"] = $values['firstname'].'.'.$values['lastname'];
$data1["email"] = $values['email'];
$data1["fullname"] = $values['firstname'].' '.$values['lastname'];
if($values['department']=='15' && $values['workunit_id']=='1'){
$data1["groupid"] = '6';
}
elseif($values['department']=='15' && $values['workunit_id']=='3'){
$data1["groupid"] = '5';
}
elseif($values['department']=='15' && $values['workunit_id']=='8'){
$data1["groupid"] = '2';
}
elseif($values['department']=='4' && $values['workunit_id']=='7'){
$data1["groupid"] = '3';
}
elseif($values['department']=='4' && $values['workunit_id']=='6'){
$data1["groupid"] = '4';
}
else{
$data1["groupid"] = '1';
}

$data1["active"] = 'enabled';
$data1["empid"] = $values['id'];

DB::Insert("csa_users", $data1 );







// Place event code here.
// Use "Add Action" button to add code snippets.
;		
} // function AfterAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before Insert Record
function BeforeInsert(&$rawvalues, &$values, &$pageObject, &$message)
{

		


//**********  Check if specific record exists  ************

$s="select * from employee where firstname='".$rawvalues['firstname']."'   and lastname='".$rawvalues['lastname']."'    and email='".$rawvalues['email']."'     ";
$r=CustomQuery($s);
$data=db_fetch_array($r);
if($data)
{
$message="this record already exist";
return false;
}
else
{
	// if dont exist do something else
$data = array();
$data["job_id"] = $values['job_id'];
$data["empid"] = $values['id'];
$data['start_date']=$values['hire_date'];
$data['workunit_id']=$values['workunit_id'];
DB::Insert("jobhistory", $data );

$data1 = array();
$data1["username"] = $values['firstname'].'.'.$values['lastname'];
$data1["email"] = $values['email'];
$data1["fullname"] = $values['firstname'].' '.$values['lastname'];
if($values['department']=='15' && $values['workunit_id']=='1'){
$data1["groupid"] = '6';
}
elseif($values['department']=='15' && $values['workunit_id']=='3'){
$data1["groupid"] = '5';
}
elseif($values['department']=='15' && $values['workunit_id']=='8'){
$data1["groupid"] = '2';
}
elseif($values['department']=='4' && $values['workunit_id']=='7'){
$data1["groupid"] = '3';
}
elseif($values['department']=='4' && $values['workunit_id']=='6'){
$data1["groupid"] = '4';
}
else{
$data1["groupid"] = '1';
}

$data1["active"] = 'enabled';
$data1["empid"] = $values['id'];

DB::Insert("csa_users", $data1 );

return true;
}




// Place event code here.
// Use "Add Action" button to add code snipp
;		
} // function BeforeInsert

		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before record added
function BeforeAdd(&$values, &$message, $inline, &$pageObject)
{

		
/*

if(strftime("%H:%M:%S")>="15:00:00"||$_SERVER["REMOTE_ADDR"]!="::1"){
// Place event code here.
// Use "Add Action" button to add code snippets.
$message="this is NOT the time to enter into the app please wait for tomorrow";
session_destroy();
}

*/


//**********  Check if specific record exists  ************


$s="select * from employee where phone='".$values['phone']."'";
$r=CustomQuery($s);
$data1=db_fetch_array($r);

if($data1)
{
	// if record exists do something
$message="this phone already exist";
return false;

}
else
{

$s="select * from employee where  email='".$values['email']."'";
$r=CustomQuery($s);
$data=db_fetch_array($r);

if($data)
{
$message="the email you use already exist";
return false;
}
else{
return true;
}


	// if dont exist do something else



}



;		
} // function BeforeAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// After record updated
function AfterEdit(&$values, $where, &$oldvalues, &$keys, $inline, &$pageObject)
{

		if($values['status']=='working'){
$sql="update csa_users set active='enabled' where empid='".$values['id']."'";
CustomQuery($sql);
}
else{
$sql="update csa_users set active='disabled' where empid='".$values['id']."'";
CustomQuery($sql);
}

// Place event code here.
// Use "Add Action" button to add code snippets.
;		
} // function AfterEdit

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

				// List page: Before process
function BeforeProcessList(&$pageObject)
{

		
/*

if(strftime("%H:%M:%S")>="15:00:00"||$_SERVER["REMOTE_ADDR"]!="::1"){
// Place event code here.
// Use "Add Action" button to add code snippets.
$message="this is NOT the time to enter into the app please wait for tomorrow";
session_destroy();
}

*/
// Place event code here.
// Use "Add Action" button to add code snippets.
;		
} // function BeforeProcessList

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
				// Add page: Before process
function BeforeProcessAdd(&$pageObject)
{

		/*

if(strftime("%H:%M:%S")>="15:00:00"||$_SERVER["REMOTE_ADDR"]!="::1"){
// Place event code here.
// Use "Add Action" button to add code snippets.
$message="this is NOT the time to enter into the app please wait for tomorrow";
session_destroy();
}

*/

// Place event code here.
// Use "Add Action" button to add code snippets.
;		
} // function BeforeProcessAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
				// Edit page: Before process
function BeforeProcessEdit(&$pageObject)
{

		
// Place event code here.
// Use "Add Action" button to add code snippets.
;		
} // function BeforeProcessEdit

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
				// Import page: Before process
function BeforeProcessImport(&$pageObject)
{

		/*

if(strftime("%H:%M:%S")>="9:00:00"||$_SERVER["REMOTE_ADDR"]!="::1"){
// Place event code here.
// Use "Add Action" button to add code snippets.
$message="this is NOT the time to enter into the app please wait for tomorrow";
session_destroy();
}

*/
// Place event code here.
// Use "Add Action" button to add code snippets.
;		
} // function BeforeProcessImport

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// List page: Before record processed
function BeforeProcessRowList(&$data, &$pageObject)
{

		


$uname=Security::getUserName();




$s="select * from employee where id='".$data['id']."'";
$r=CustomQuery($s);
$dd2=db_fetch_array($r);



$empdpt=$dd2['department'];
$approveid=$dd2['manager_id'];


$s="select * from csa_users where username='".$uname."'";
$r=CustomQuery($s);
$dd1=db_fetch_array($r);

if($dd1['groupid']=='3'){

return true;
}
elseif($dd1['groupid']=='2'){
$deptmanagerid=$dd1['empid'];
$rss2=DB::Query("select * from employee where id='".$deptmanagerid."'");
$dd3=$rss2->fetchAssoc();
$dptmanagerdpt=$dd3['department'];
if($empdpt==$dptmanagerdpt){
return true;

}
else
return false;
}
elseif($dd1['groupid']=='5'){
return true;
}



// Place event code here.
// Use "Add Action" button to add code snippets.


;		
} // function BeforeProcessRowList

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>
