<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */
 
 class eventclass_mode22  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["AfterAdd"]=true;

		$this->events["BeforeAdd"]=true;

		$this->events["BeforeProcessAdd"]=true;


	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// After record added
function AfterAdd(&$values, &$keys, $inline, &$pageObject)
{

		

//**********  Insert a record into another table  ************

$data = array();
$data["employee_id"] = $values['receiver_id'];
$data["ea_id"] = $values['ea_id'];
$data["issued_date"] = $values['issued_date'];
$data["asset_id"] = $values['asset_id'];
$data["transaction"]='incomplet';
DB::Insert("eaempassets", $data );

$sql="update request_info set taked='yes' where employee_id='".$values['receiver_id']."' and asset_id='".$values['asset_id']."'";
CustomQuery($sql);

$s="update asset set taken='yes' where asset_id='".$values['asset_id']."'";

CustomQuery($s);


// Place event code here.
// Use "Add Action" button to add code snippets.
;		
} // function AfterAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before record added
function BeforeAdd(&$values, &$message, $inline, &$pageObject)
{

		
$s="select * from asset where asset_id='".$values['asset_id']."'";
$r=CustomQuery($s);
$d=db_fetch_array($r);

$s1="select * from model19frompurchase where id='".$values['asset_id']."'";
$r1=CustomQuery($s1);
$d12=db_fetch_array($r1);
$values['unitprice']=$d12['price'];
$values['serial']=$d['asset_serial'];

$values['totalprice']=$values['quantity']*$values['unitprice'];


$uname=Security::getUserName();





$sql = "select * from csa_users where username='".$uname."'";
$rs = CustomQuery($sql);
$data = db_fetch_array($rs);



if($data['empid']==$values['ea_id']){
return true;
}
else{
$message="please choose you'r own id for signture";
return false;
}

// Place event code here.
// Use "Add Action" button to add code snippets.


;		
} // function BeforeAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
				// Add page: Before process
function BeforeProcessAdd(&$pageObject)
{

		
/*

if(strftime("%H:%M:%S")>="15:00:00"||$_SERVER["REMOTE_ADDR"]!="::1"){
// Place event code here.
// Use "Add Action" button to add code snippets.
$message="this is NOT the time to enter into the app please wait for tomorrow";
session_destroy();
}

*/
// Place event code here.
// Use "Add Action" button to add code snippets.
;		
} // function BeforeProcessAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>
