<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */
 
 class eventclass_model19frompurchase  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["AfterEdit"]=true;

		$this->events["AfterAdd"]=true;

		$this->events["BeforeProcessList"]=true;

		$this->events["BeforeProcessAdd"]=true;

		$this->events["BeforeAdd"]=true;


	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// After record updated
function AfterEdit(&$values, $where, &$oldvalues, &$keys, $inline, &$pageObject)
{

		$sql = "update asset set asset_name='".$values['as_name']."' and asset_serial='".$values['serial']."'  and asset_model='".$values['model']."'   and manufactured_date='".$values['manufactured_date']."' and manufacturer='".$values['manufacturer']."' and category_id='".$values['category_id']."' and suplier_id='".$values['supplier_id']."' and image='".$values['photo']."' where asset_name=".$values['as_name']." and asset_model=".$values['model']."and asset_serial=".$values['serial'];

CustomQuery($sql);


// Place event code here.
// Use "Add Action" button to add code snippets.
;		
} // function AfterEdit

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// After record added
function AfterAdd(&$values, &$keys, $inline, &$pageObject)
{

		
/*

if(strftime("%H:%M:%S")>="15:00:00"||$_SERVER["REMOTE_ADDR"]!="::1"){
// Place event code here.
// Use "Add Action" button to add code snippets.
$message="this is NOT the time to enter into the app please wait for tomorrow";
session_destroy();
}

*/
//**********  Insert a record into another table  ************



//**********  Insert a record into another table  ************

$data = array();
$data["item_id"] = $values['id'];
$data["price"] = $values['price'];
$data["sourceinfo_id"] = $values['supplier_id'];
$data["pricedate"] = strftime("%Y-%m-%d");
DB::Insert("price", $data);


$data2 = array();
$data2["asset_name"] = $values['as_name'];
$data2["asset_model"] = $values['model'];
$data2["asset_serial"] = $values['serial'];
$data2["manufactured_date"] = $values['manufactured_date'];
$data2["manufacturer"] = $values['manufacturer'];
$data2["category_id"] = $values['category_id'];
$data2["suplier_id"] = $values['supplier_id'];
$data2["status_id"] = '1';
$data2["registration_date"] = $values['received_date'];
$data2["purchased_date"] = $values['purchased_date'];
$data2["image"] = $values['photo'];
$data2["taken"] = 'no';
$data2['type_id']=$values['type_id'];
DB::Insert("asset", $data2 );

$data1 = array();
$data1["employee_id"] = $values['donor_id'];
$data1["ea_id"] = $values['receiver_id'];
$data1["transfer_date"] = $values['received_date'];
$data1["asset_id"] = $values['id'];
DB::Insert("eaempassets", $data1 );





// Place event code here.
// Use "Add Action" button to add code snippets.
;		
} // function AfterAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

				// List page: Before process
function BeforeProcessList(&$pageObject)
{

		
/*

if(strftime("%H:%M:%S")>="15:00:00"||$_SERVER["REMOTE_ADDR"]!="::1"){
// Place event code here.
// Use "Add Action" button to add code snippets.
$message="this is NOT the time to enter into the app please wait for tomorrow";
session_destroy();
}


*/
// Place event code here.
// Use "Add Action" button to add code snippets.
;		
} // function BeforeProcessList

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
				// Add page: Before process
function BeforeProcessAdd(&$pageObject)
{

		/*

if(strftime("%H:%M:%S")>="15:00:00"||$_SERVER["REMOTE_ADDR"]!="::1"){
// Place event code here.
// Use "Add Action" button to add code snippets.
$message="this is NOT the time to enter into the app please wait for tomorrow";
session_destroy();
}

*/
// Place event code here.
// Use "Add Action" button to add code snippets.
;		
} // function BeforeProcessAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before record added
function BeforeAdd(&$values, &$message, $inline, &$pageObject)
{

		
$userData=Security::getUserName();


$sql12 = "select * from csa_users where username='".$userData."'";
$rs11 = CustomQuery($sql12);
$dd1 = db_fetch_array($rs11);


$sql122 = "select * from asset where asset_name='".$values['as_name']."' and asset_model='".$values['model']."'    and asset_serial='".$values['serial']."'";
$rs12 = CustomQuery($sql122);
$dd2 = db_fetch_array($rs12);
if($dd2){
$message="the asset you insert is already registered";
return false;
}else{
if($dd1['empid']==$values['receiver_id']){
return true;}
else{
$message="this must be your userid";
 return false;}
}

// Place event code here.
// Use "Add Action" button to add code snippets.

return true;
;		
} // function BeforeAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>
