<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */
 
 class eventclass_model19fromemployee  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["AfterAdd"]=true;

		$this->events["BeforeProcessAdd"]=true;

		$this->events["BeforeProcessList"]=true;

		$this->events["BeforeAdd"]=true;


	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// After record added
function AfterAdd(&$values, &$keys, $inline, &$pageObject)
{

		
//**********  Insert a record into another table  ************


$sql="update eaempassets set transaction='complet' where asset_id='".$values['asset_id']."' and employee_id='".$values['donor_id']."'";
CustomQuery($sql);

$sql1="update eaempassets set returned_date='2020-01-30' where asset_id='".$values['asset_id']."' and employee_id='".$values['donor_id']."'";
CustomQuery($sql1);


$s="update asset set taken='no' and status_id='".$values['status']."' where asset_id='".$values['asset_id']."' and   asset_model='".$values['model']."' and asset_serial='".$values['serial']."'";

CustomQuery($s);
$s1="update asset set status_id='".$values['status']."' where asset_id='".$values['asset_id']."' and   asset_model='".$values['model']."' and asset_serial='".$values['serial']."'";

CustomQuery($s1);
// Place event code here.
// Use "Add Action" button to add code snippets.
;		
} // function AfterAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
				// Add page: Before process
function BeforeProcessAdd(&$pageObject)
{

		/*

if(strftime("%H:%M:%S")>="15:00:00"||$_SERVER["REMOTE_ADDR"]!="::1"){
// Place event code here.
// Use "Add Action" button to add code snippets.
$message="this is NOT the time to enter into the app please wait for tomorrow";
session_destroy();
}

*/
// Place event code here.
// Use "Add Action" button to add code snippets.
;		
} // function BeforeProcessAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

				// List page: Before process
function BeforeProcessList(&$pageObject)
{

		
/*

if(strftime("%H:%M:%S")>="15:00:00"||$_SERVER["REMOTE_ADDR"]!="::1"){
// Place event code here.
// Use "Add Action" button to add code snippets.
$message="this is NOT the time to enter into the app please wait for tomorrow";
session_destroy();
}
*/
// Place event code here.
// Use "Add Action" button to add code snippets.
;		
} // function BeforeProcessList

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before record added
function BeforeAdd(&$values, &$message, $inline, &$pageObject)
{

		
$s="select * from checkapproval where empid='".$values['donor_id']."' and assetid='".$values['asset_id']."'";
$rss=CustomQuery($s);
$dd=db_fetch_array($rss);

$s="select * from employee where id='".$dd['ictdeptemp']."'";
$rss=CustomQuery($s);
$dd1=db_fetch_array($rss);

$s="select * from csa_users where empid='".$dd['ictdeptemp']."'";
$rss=CustomQuery($s);
$dd11=db_fetch_array($rss);

$s="select * from employee where id='".$dd['ictdeptmanager']."'";
$rss=CustomQuery($s);
$dd2=db_fetch_array($rss);

$s="select * from csa_users where empid='".$dd['ictdeptmanager']."'";
$rss=CustomQuery($s);
$dd22=db_fetch_array($rss);

if($dd1['department']=='15' && $dd2['department']=='15'){
if($dd11['groupid']=='6' && $dd22['groupid']=='2'){

return true;
}

}
else{
$message="first this employee must get fully check approval from ict department for the device";
return false;}
// Place event code here.
// Use "Add Action" button to add code snippets.

;		
} // function BeforeAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>
