<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */
 
 class eventclass_request_info  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["BeforeEdit"]=true;

		$this->events["BeforeProcessList"]=true;

		$this->events["BeforeProcessEdit"]=true;

		$this->events["BeforeProcessRowList"]=true;

		$this->events["ProcessValuesEdit"]=true;


	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before record updated
function BeforeEdit(&$values, $where, &$oldvalues, &$keys, &$message, $inline, &$pageObject)
{

		$uname=Security::getUserName();
$data1 =$values['approve_status_from_dept_manager'];
$data2 =$values['approve_status_from_asset_dept_manager'];


$s="select * from employee where id='".$values['employee_id']."'";
$rr=CustomQuery($s);
$d=db_fetch_array($rr);

$sql = "select * from csa_users where username='".$uname."'";
$rs = CustomQuery($sql);
$data = db_fetch_array($rs);
if($data['groupid']=='3'){
if($d['manager_id']==$data['empid']){
if($data['empid']==$data2 && $data['empid']==$data1){
return true;
}
else{
$message="this is not your username please choose your own username";
return false;
}}else{

if($data['empid']==$data2){
return true;
}
else{
$message="this is not your username please choose your own username";
return false;
}}


// Place event code here.
// Use "Add Action" button to add code snippets.

}
else{
if($data['empid']==$data1){
return true;
}
else{
$message="this is not your username please choose your own username";
return false;
}

}

// Place event code here.
// Use "Add Action" button to add code snippets.


;		
} // function BeforeEdit

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

				// List page: Before process
function BeforeProcessList(&$pageObject)
{

		/*

if(strftime("%H:%M:%S")>="15:00:00"||$_SERVER["REMOTE_ADDR"]!="::1"){
// Place event code here.
// Use "Add Action" button to add code snippets.
$message="this is NOT the time to enter into the app please wait for tomorrow";
session_destroy();
}

*/
$uname=Security::getUserName();

$rss1=DB::Query("select * from csa_users where username='".$uname."'");
$dd1=$rss1->fetchAssoc();


if ($dd1['groupid']!="3"){
  $pageObject->hideField("approve_status_from_asset_dept_manager");
}

// Place event code here.
// Use "Add Action" button to add code snippets.
;		
} // function BeforeProcessList

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
				// Edit page: Before process
function BeforeProcessEdit(&$pageObject)
{

		/*

if(strftime("%H:%M:%S")>="15:00:00"||$_SERVER["REMOTE_ADDR"]!="::1"){
// Place event code here.
// Use "Add Action" button to add code snippets.
$message="this is NOT the time to enter into the app please wait for tomorrow";
session_destroy();
}


*/

$uname=Security::getUserName();

$rss1=DB::Query("select * from csa_users where username='".$uname."'");
$dd1=$rss1->fetchAssoc();
$rss2=DB::Query("select * from employee where id='".$data['employee_id']."'");
$dd2=$rss2->fetchAssoc();
$empdpt=$dd2['department'];
$approveid=$dd2['manager_id'];

if ($dd1['groupid']!="3"){
  $pageObject->hideField("approve_status_from _asset_dept_manager");
}


// Place event code here.
// Use "Add Action" button to add code snippets.
;		
} // function BeforeProcessEdit

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// List page: Before record processed
function BeforeProcessRowList(&$data, &$pageObject)
{

		
$uname=Security::getUserName();


$rss2=DB::Query("select * from employee where id='".$data['employee_id']."'");
$dd2=$rss2->fetchAssoc();
$empdpt=$dd2['department'];
$approveid=$dd2['manager_id'];


$rss1=DB::Query("select * from csa_users where username='".$uname."'");
$dd1=$rss1->fetchAssoc();
if($dd1['groupid']=='3'){
$assetmanagerid=$dd1['empid'];
$rss2=DB::Query("select * from employee where id='".$assetmanagerid."'");
$dd2=$rss2->fetchAssoc();
$assetdptmanagerdpt=$dd2['department'];


if($empdpt==$assetdptmanagerdpt || $data['approve_status_from_dept_manager']==$approveid){
return true;
}
else
return false;

}
elseif($dd1['groupid']=='2'){
$deptmanagerid=$dd1['empid'];
$rss2=DB::Query("select * from employee where id='".$deptmanagerid."'");
$dd3=$rss2->fetchAssoc();
$dptmanagerdpt=$dd3['department'];
if($empdpt==$dptmanagerdpt){
return true;

}
else
return false;
}



;		
} // function BeforeProcessRowList

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Process record values
function ProcessValuesEdit(&$values, &$pageObject)
{

		


$uname=Security::getUserName();

$rss1=DB::Query("select * from csa_users where username='".$uname."'");
$dd1=$rss1->fetchAssoc();
$rss2=DB::Query("select * from employee where id='".$values['employee_id']."'");
$dd2=$rss2->fetchAssoc();
$empdpt=$dd2['department'];
$approveid=$dd2['manager_id'];

if($dd1['empid']==$approveid&& $dd1['groupid']!='3'){
$pageObject->hideField("approve_status_from_asset_dept_manager");
}
elseif($dd1['groupid']=='3'&& $dd1['empid']!=$approveid){
$pageObject->hideField("approve_status_from_dept_manager");
}




// Place event code here.
// Use "Add Action" button to add code snippets.
;		
} // function ProcessValuesEdit

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>
