<?php
			$optionsArray = array( 'welcome' => array( 'welcomeItems' => array( 'logo' => array( 'menutItem' => false ),
'list_options' => array( 'menutItem' => false ),
'loginform_login' => array( 'menutItem' => false ),
'username_button' => array( 'menutItem' => false ),
'breadcrumb' => array( 'menutItem' => false ),
'welcome_item1' => array( 'menutItem' => true,
'group' => false,
'items' => null,
'table' => 'asset',
'page' => 'list' ),
'welcome_item2' => array( 'menutItem' => true,
'group' => false,
'items' => null,
'table' => 'assetcategory',
'page' => 'list' ),
'welcome_item5' => array( 'menutItem' => true,
'group' => false,
'items' => null,
'table' => 'assetsuppliers',
'page' => 'list' ),
'welcome_item6' => array( 'menutItem' => true,
'group' => false,
'items' => null,
'table' => 'csa1_uggroups',
'page' => 'list' ),
'welcome_item7' => array( 'menutItem' => true,
'group' => false,
'items' => null,
'table' => 'csa_audit',
'page' => 'list' ),
'welcome_item8' => array( 'menutItem' => true,
'group' => false,
'items' => null,
'table' => 'csa_settings',
'page' => 'list' ),
'welcome_item10' => array( 'menutItem' => true,
'group' => false,
'items' => null,
'table' => 'csa_locking',
'page' => 'list' ),
'welcome_item11' => array( 'menutItem' => true,
'group' => false,
'items' => null,
'table' => 'csa_uggroups',
'page' => 'list' ),
'welcome_item12' => array( 'menutItem' => true,
'group' => false,
'items' => null,
'table' => 'csa_users',
'page' => 'list' ),
'welcome_item13' => array( 'menutItem' => true,
'group' => false,
'items' => null,
'table' => 'departments',
'page' => 'list' ),
'welcome_item14' => array( 'menutItem' => true,
'group' => false,
'items' => null,
'table' => 'eaempassets',
'page' => 'list' ),
'welcome_item16' => array( 'menutItem' => true,
'group' => false,
'items' => null,
'table' => 'jobhistory',
'page' => 'list' ),
'welcome_item17' => array( 'menutItem' => true,
'group' => false,
'items' => null,
'table' => 'jobs',
'page' => 'list' ),
'welcome_item19' => array( 'menutItem' => true,
'group' => false,
'items' => null,
'table' => 'model19fromemployee',
'page' => 'list' ),
'welcome_item20' => array( 'menutItem' => true,
'group' => false,
'items' => null,
'table' => 'model19frompurchase',
'page' => 'list' ),
'welcome_item21' => array( 'menutItem' => true,
'group' => false,
'items' => null,
'table' => 'model20',
'page' => 'list' ),
'welcome_item22' => array( 'menutItem' => true,
'group' => false,
'items' => null,
'table' => 'price',
'page' => 'list' ),
'welcome_item23' => array( 'menutItem' => true,
'group' => false,
'items' => null,
'table' => 'request_info',
'page' => 'list' ),
'welcome_item24' => array( 'menutItem' => true,
'group' => false,
'items' => null,
'table' => 'sourceinfo',
'page' => 'list' ),
'welcome_item25' => array( 'menutItem' => true,
'group' => false,
'items' => null,
'table' => 'workunit',
'page' => 'list' ),
'welcome_item' => array( 'menutItem' => true,
'group' => false,
'items' => null,
'table' => 'Dashboard',
'page' => 'dashboard' ),
'welcome_item9' => array( 'menutItem' => true,
'group' => false,
'items' => null,
'table' => 'employee',
'page' => 'list' ),
'welcome_item26' => array( 'menutItem' => true,
'group' => false,
'items' => null,
'table' => 'app_logs',
'page' => 'list' ),
'welcome_item18' => array( 'menutItem' => true,
'group' => false,
'items' => null,
'table' => 'mode22',
'page' => 'list' ),
'welcome_item27' => array( 'menutItem' => true,
'group' => false,
'items' => null,
'table' => 'checkapproval',
'page' => 'list' ),
'welcome_item3' => array( 'menutItem' => true,
'group' => false,
'items' => null,
'table' => 'asset in store',
'page' => 'list' ) ) ),
'fields' => array( 'gridFields' => array(  ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array(  ) ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array( 'list_options',
'loginform_login',
'username_button',
'logo' ),
'above-grid' => array( 'breadcrumb' ),
'grid' => array( 'welcome_item1',
'welcome_item2',
'welcome_item5',
'welcome_item6',
'welcome_item7',
'welcome_item8',
'welcome_item10',
'welcome_item11',
'welcome_item12',
'welcome_item13',
'welcome_item14',
'welcome_item16',
'welcome_item17',
'welcome_item19',
'welcome_item20',
'welcome_item21',
'welcome_item22',
'welcome_item23',
'welcome_item24',
'welcome_item25',
'welcome_item',
'welcome_item9',
'welcome_item26',
'welcome_item18',
'welcome_item27',
'welcome_item3' ) ),
'formXtTags' => array( 'above-grid' => array( 'breadcrumb' ) ),
'itemForms' => array( 'list_options' => 'supertop',
'loginform_login' => 'supertop',
'username_button' => 'supertop',
'logo' => 'supertop',
'breadcrumb' => 'above-grid',
'welcome_item1' => 'grid',
'welcome_item2' => 'grid',
'welcome_item5' => 'grid',
'welcome_item6' => 'grid',
'welcome_item7' => 'grid',
'welcome_item8' => 'grid',
'welcome_item10' => 'grid',
'welcome_item11' => 'grid',
'welcome_item12' => 'grid',
'welcome_item13' => 'grid',
'welcome_item14' => 'grid',
'welcome_item16' => 'grid',
'welcome_item17' => 'grid',
'welcome_item19' => 'grid',
'welcome_item20' => 'grid',
'welcome_item21' => 'grid',
'welcome_item22' => 'grid',
'welcome_item23' => 'grid',
'welcome_item24' => 'grid',
'welcome_item25' => 'grid',
'welcome_item' => 'grid',
'welcome_item9' => 'grid',
'welcome_item26' => 'grid',
'welcome_item18' => 'grid',
'welcome_item27' => 'grid',
'welcome_item3' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array( 'list_options' => 3,
'loginform_login' => 3,
'username_button' => 3 ) ),
'itemsByType' => array( 'logo' => array( 'logo' ),
'breadcrumb' => array( 'breadcrumb' ),
'welcome_item' => array( 'welcome_item1',
'welcome_item2',
'welcome_item5',
'welcome_item6',
'welcome_item7',
'welcome_item8',
'welcome_item10',
'welcome_item11',
'welcome_item12',
'welcome_item13',
'welcome_item14',
'welcome_item16',
'welcome_item17',
'welcome_item18',
'welcome_item19',
'welcome_item20',
'welcome_item21',
'welcome_item22',
'welcome_item23',
'welcome_item24',
'welcome_item25',
'welcome_item',
'welcome_item9',
'welcome_item26',
'welcome_item27',
'welcome_item3' ),
'list_options' => array( 'list_options' ),
'lang_selector' => array( 'lang_selector' ),
'loginform_login' => array( 'loginform_login' ),
'username_button' => array( 'username_button' ),
'logout_link' => array( 'logout_link' ),
'changepassword_link' => array( 'changepassword_link' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 1 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'menu',
'type' => 'menu',
'layoutId' => 'topbar',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'menu-topbar-menu',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c' ),
array( 'cell' => 'c1',
'colspan' => 1 ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c2',
'items' => array( 'list_options',
'loginform_login',
'username_button' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c' => array( 'model' => 'c1',
'items' => array( 'logo' ),
'nowrap' => false ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'empty-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'breadcrumb' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'welcome',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'welcome_item1',
'welcome_item2',
'welcome_item5',
'welcome_item6',
'welcome_item7',
'welcome_item8',
'welcome_item10',
'welcome_item11',
'welcome_item12',
'welcome_item13',
'welcome_item14',
'welcome_item16',
'welcome_item17',
'welcome_item19',
'welcome_item20',
'welcome_item21',
'welcome_item22',
'welcome_item23',
'welcome_item24',
'welcome_item25',
'welcome_item',
'welcome_item9',
'welcome_item26',
'welcome_item18',
'welcome_item27',
'welcome_item3' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'logo' => array( 'type' => 'logo' ),
'breadcrumb' => array( 'type' => 'breadcrumb' ),
'welcome_item1' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'asset',
'linkPage' => 'list',
'linkText' => array( 'table' => 'asset',
'type' => 6 ),
'linkIcon' => array( 'glyph' => 'hand-right' ),
'linkComments' => array( 'label' => 'ASSET_DESCRIPTION1',
'type' => 1 ),
'background' => '#6B8E23' ),
'welcome_item2' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'assetcategory',
'linkPage' => 'list',
'linkText' => array( 'table' => 'assetcategory',
'type' => 6 ),
'linkIcon' => array( 'glyph' => 'hand-right' ),
'linkComments' => array( 'label' => 'ASSETCATEGORY_DESCRIPTION1',
'type' => 1 ),
'background' => '#CD853F' ),
'welcome_item5' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'assetsuppliers',
'linkPage' => 'list',
'linkText' => array( 'table' => 'assetsuppliers',
'type' => 6 ),
'linkIcon' => array( 'glyph' => 'hand-right' ),
'background' => '#7B68EE' ),
'welcome_item6' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'csa1_uggroups',
'linkPage' => 'list',
'linkText' => array( 'table' => 'csa1_uggroups',
'type' => 6 ),
'linkIcon' => array( 'glyph' => 'fire' ),
'background' => '#D2691E' ),
'welcome_item7' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'csa_audit',
'linkPage' => 'list',
'linkText' => array( 'table' => 'csa_audit',
'type' => 6 ),
'background' => '#D2AF80' ),
'welcome_item8' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'csa_settings',
'linkPage' => 'list',
'linkText' => array( 'table' => 'csa_settings',
'type' => 6 ),
'background' => '#778899' ),
'welcome_item10' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'csa_locking',
'linkPage' => 'list',
'linkText' => array( 'table' => 'csa_locking',
'type' => 6 ),
'background' => '#6B8E23' ),
'welcome_item11' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'csa_uggroups',
'linkPage' => 'list',
'linkText' => array( 'table' => 'csa_uggroups',
'type' => 6 ),
'background' => '#D2691E' ),
'welcome_item12' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'csa_users',
'linkPage' => 'list',
'linkText' => array( 'table' => 'csa_users',
'type' => 6 ),
'background' => '#6493EA' ),
'welcome_item13' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'departments',
'linkPage' => 'list',
'linkText' => array( 'table' => 'departments',
'type' => 6 ),
'background' => '#4682B4' ),
'welcome_item14' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'eaempassets',
'linkPage' => 'list',
'linkText' => array( 'table' => 'eaempassets',
'type' => 6 ),
'background' => '#E67349' ),
'welcome_item16' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'jobhistory',
'linkPage' => 'list',
'linkText' => array( 'table' => 'jobhistory',
'type' => 6 ),
'background' => '#3CB371' ),
'welcome_item17' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'jobs',
'linkPage' => 'list',
'linkText' => array( 'table' => 'jobs',
'type' => 6 ),
'background' => '#2F4F4F' ),
'welcome_item18' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'mode22',
'linkPage' => 'list',
'linkText' => array( 'table' => 'mode22',
'type' => 6 ),
'background' => '#4169E1' ),
'welcome_item19' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'model19fromemployee',
'linkPage' => 'list',
'linkText' => array( 'table' => 'model19fromemployee',
'type' => 6 ),
'background' => '#4169E1' ),
'welcome_item20' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'model19frompurchase',
'linkPage' => 'list',
'linkText' => array( 'table' => 'model19frompurchase',
'type' => 6 ),
'background' => '#008B8B' ),
'welcome_item21' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'model20',
'linkPage' => 'list',
'linkText' => array( 'table' => 'model20',
'type' => 6 ),
'background' => '#4682B4' ),
'welcome_item22' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'price',
'linkPage' => 'list',
'linkText' => array( 'table' => 'price',
'type' => 6 ),
'background' => '#1E90FF' ),
'welcome_item23' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'request_info',
'linkPage' => 'list',
'linkText' => array( 'table' => 'request_info',
'type' => 6 ),
'background' => '#D2691E' ),
'welcome_item24' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'sourceinfo',
'linkPage' => 'list',
'linkText' => array( 'table' => 'sourceinfo',
'type' => 6 ),
'background' => '#D2AF80' ),
'welcome_item25' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'workunit',
'linkPage' => 'list',
'linkText' => array( 'table' => 'workunit',
'type' => 6 ),
'background' => '#CD853F' ),
'list_options' => array( 'type' => 'list_options',
'items' => array( 'lang_selector' ) ),
'lang_selector' => array( 'type' => 'lang_selector' ),
'loginform_login' => array( 'type' => 'loginform_login',
'popup' => true ),
'username_button' => array( 'type' => 'username_button',
'items' => array( 'logout_link',
'changepassword_link' ) ),
'logout_link' => array( 'type' => 'logout_link' ),
'changepassword_link' => array( 'type' => 'changepassword_link' ),
'welcome_item' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'Dashboard',
'linkPage' => 'dashboard',
'linkText' => array( 'table' => 'Dashboard',
'type' => 6 ),
'background' => '#6DA5C8' ),
'welcome_item9' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'employee',
'linkPage' => 'list',
'linkText' => array( 'table' => 'employee',
'type' => 6 ),
'background' => '#1E90FF' ),
'welcome_item26' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'app_logs',
'linkPage' => 'list',
'linkText' => array( 'table' => 'app_logs',
'type' => 6 ),
'background' => '#D2AF80' ),
'welcome_item27' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'checkapproval',
'linkPage' => 'list',
'linkText' => array( 'table' => 'checkapproval',
'type' => 6 ),
'background' => '#D2AF80' ),
'welcome_item3' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'asset in store',
'linkPage' => 'list',
'linkText' => array( 'table' => 'asset in store',
'type' => 6 ),
'background' => '#3CB371' ) ),
'dbProps' => array(  ),
'version' => 4 );
		?>