<?php
			$optionsArray = array( 'totals' => array( 'log_id' => array( 'totalsType' => '' ),
'Timestamp' => array( 'totalsType' => '' ),
'Action' => array( 'totalsType' => '' ),
'TableName' => array( 'totalsType' => '' ),
'RecordID' => array( 'totalsType' => '' ),
'SqlQuery' => array( 'totalsType' => '' ),
'UserID' => array( 'totalsType' => '' ),
'ServerIP' => array( 'totalsType' => '' ),
'RequestUrl' => array( 'totalsType' => '' ),
'RequestData' => array( 'totalsType' => '' ),
'RequestCompleted' => array( 'totalsType' => '' ),
'RequestMsg' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'log_id',
'Timestamp',
'Action',
'TableName',
'RecordID',
'SqlQuery',
'UserID',
'ServerIP',
'RequestUrl',
'RequestData',
'RequestCompleted',
'RequestMsg' ),
'exportFields' => array( 'log_id',
'Timestamp',
'Action',
'TableName',
'RecordID',
'SqlQuery',
'UserID',
'ServerIP',
'RequestUrl',
'RequestData',
'RequestCompleted',
'RequestMsg' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'log_id' => array( 'export_field' ),
'Timestamp' => array( 'export_field1' ),
'Action' => array( 'export_field2' ),
'TableName' => array( 'export_field3' ),
'RecordID' => array( 'export_field4' ),
'SqlQuery' => array( 'export_field5' ),
'UserID' => array( 'export_field6' ),
'ServerIP' => array( 'export_field7' ),
'RequestUrl' => array( 'export_field8' ),
'RequestData' => array( 'export_field9' ),
'RequestCompleted' => array( 'export_field10' ),
'RequestMsg' => array( 'export_field11' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'export_header' ),
'grid' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11' ),
'footer' => array( 'export_export',
'export_cancel' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'export_header' => 'top',
'export_field' => 'grid',
'export_field1' => 'grid',
'export_field2' => 'grid',
'export_field3' => 'grid',
'export_field4' => 'grid',
'export_field5' => 'grid',
'export_field6' => 'grid',
'export_field7' => 'grid',
'export_field8' => 'grid',
'export_field9' => 'grid',
'export_field10' => 'grid',
'export_field11' => 'grid',
'export_export' => 'footer',
'export_cancel' => 'footer' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'export_header' => array( 'export_header' ),
'export_export' => array( 'export_export' ),
'export_cancel' => array( 'export_cancel' ),
'export_field' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'export' => array( 'format' => 2,
'selectFields' => false,
'delimiter' => ',',
'selectDelimiter' => false,
'exportFileTypes' => array( 'excel' => true,
'word' => true,
'csv' => true,
'xml' => false ) ) );
			$pageArray = array( 'id' => 'export',
'type' => 'export',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'export-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'export-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'export-footer',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'export_export',
'export_cancel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'export_header' => array( 'type' => 'export_header' ),
'export_export' => array( 'type' => 'export_export' ),
'export_cancel' => array( 'type' => 'export_cancel' ),
'export_field' => array( 'field' => 'log_id',
'type' => 'export_field' ),
'export_field1' => array( 'field' => 'Timestamp',
'type' => 'export_field' ),
'export_field2' => array( 'field' => 'Action',
'type' => 'export_field' ),
'export_field3' => array( 'field' => 'TableName',
'type' => 'export_field' ),
'export_field4' => array( 'field' => 'RecordID',
'type' => 'export_field' ),
'export_field5' => array( 'field' => 'SqlQuery',
'type' => 'export_field' ),
'export_field6' => array( 'field' => 'UserID',
'type' => 'export_field' ),
'export_field7' => array( 'field' => 'ServerIP',
'type' => 'export_field' ),
'export_field8' => array( 'field' => 'RequestUrl',
'type' => 'export_field' ),
'export_field9' => array( 'field' => 'RequestData',
'type' => 'export_field' ),
'export_field10' => array( 'field' => 'RequestCompleted',
'type' => 'export_field' ),
'export_field11' => array( 'field' => 'RequestMsg',
'type' => 'export_field' ) ),
'dbProps' => array(  ),
'version' => 4,
'exportFormat' => 2,
'exportDelimiter' => ',',
'exportSelectDelimiter' => false,
'exportSelectFields' => false );
		?>