<?php
			$optionsArray = array( 'pdf' => array( 'pdfView' => true,
'orientation' => 'portrait',
'scale' => 100 ),
'fields' => array( 'gridFields' => array( 'asset_name',
'asset_model',
'asset_serial',
'manufactured_date',
'manufacturer',
'category_id',
'suplier_id',
'status_id',
'registration_date',
'purchased_date',
'image',
'taken',
'asset_id' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'asset_name' => array( 'integrated_edit_field1' ),
'asset_model' => array( 'integrated_edit_field2' ),
'asset_serial' => array( 'integrated_edit_field3' ),
'manufactured_date' => array( 'integrated_edit_field4' ),
'manufacturer' => array( 'integrated_edit_field5' ),
'category_id' => array( 'integrated_edit_field6' ),
'suplier_id' => array( 'integrated_edit_field7' ),
'status_id' => array( 'integrated_edit_field8' ),
'registration_date' => array( 'integrated_edit_field9' ),
'purchased_date' => array( 'integrated_edit_field10' ),
'image' => array( 'integrated_edit_field11' ),
'taken' => array( 'integrated_edit_field12' ),
'asset_id' => array( 'integrated_edit_field' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'top' => array( 'view_header' ),
'above-grid' => array(  ),
'below-grid' => array( 'view_back_list',
'view_close',
'prev',
'next',
'hamburger' ),
'grid' => array( 'integrated_edit_field1',
'integrated_edit_field12',
'integrated_edit_field10',
'integrated_edit_field9',
'integrated_edit_field8',
'integrated_edit_field7',
'integrated_edit_field11',
'integrated_edit_field6',
'integrated_edit_field4',
'integrated_edit_field5',
'integrated_edit_field3',
'integrated_edit_field2',
'integrated_edit_field' ) ),
'formXtTags' => array( 'above-grid' => array(  ) ),
'itemForms' => array( 'view_header' => 'top',
'view_back_list' => 'below-grid',
'view_close' => 'below-grid',
'prev' => 'below-grid',
'next' => 'below-grid',
'hamburger' => 'below-grid',
'integrated_edit_field1' => 'grid',
'integrated_edit_field12' => 'grid',
'integrated_edit_field10' => 'grid',
'integrated_edit_field9' => 'grid',
'integrated_edit_field8' => 'grid',
'integrated_edit_field7' => 'grid',
'integrated_edit_field11' => 'grid',
'integrated_edit_field6' => 'grid',
'integrated_edit_field4' => 'grid',
'integrated_edit_field5' => 'grid',
'integrated_edit_field3' => 'grid',
'integrated_edit_field2' => 'grid',
'integrated_edit_field' => 'grid' ),
'itemLocations' => array( 'integrated_edit_field1' => array( 'location' => 'grid',
'cellId' => 'c' ),
'integrated_edit_field12' => array( 'location' => 'grid',
'cellId' => 'c7' ),
'integrated_edit_field10' => array( 'location' => 'grid',
'cellId' => 'c10' ),
'integrated_edit_field9' => array( 'location' => 'grid',
'cellId' => 'c13' ),
'integrated_edit_field8' => array( 'location' => 'grid',
'cellId' => 'c16' ),
'integrated_edit_field7' => array( 'location' => 'grid',
'cellId' => 'c19' ),
'integrated_edit_field11' => array( 'location' => 'grid',
'cellId' => 'c21' ),
'integrated_edit_field6' => array( 'location' => 'grid',
'cellId' => 'c22' ),
'integrated_edit_field4' => array( 'location' => 'grid',
'cellId' => 'c25' ),
'integrated_edit_field5' => array( 'location' => 'grid',
'cellId' => 'c28' ),
'integrated_edit_field3' => array( 'location' => 'grid',
'cellId' => 'c31' ),
'integrated_edit_field2' => array( 'location' => 'grid',
'cellId' => 'c34' ),
'integrated_edit_field' => array( 'location' => 'grid',
'cellId' => 'c30' ) ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'view_header' => array( 'view_header' ),
'view_back_list' => array( 'view_back_list' ),
'view_close' => array( 'view_close' ),
'hamburger' => array( 'hamburger' ),
'integrated_edit_field' => array( 'integrated_edit_field1',
'integrated_edit_field2',
'integrated_edit_field3',
'integrated_edit_field4',
'integrated_edit_field5',
'integrated_edit_field6',
'integrated_edit_field7',
'integrated_edit_field8',
'integrated_edit_field9',
'integrated_edit_field10',
'integrated_edit_field11',
'integrated_edit_field12',
'integrated_edit_field' ),
'view_pdf' => array( 'view_pdf' ),
'next' => array( 'next' ),
'prev' => array( 'prev' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'c21' => array( 'cols' => array( 0 ),
'rows' => array( 0,
1,
2,
3,
4,
5,
6,
7,
8,
9,
10,
11 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field11' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c30' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field1' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c34' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field2' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c31' => array( 'cols' => array( 1 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field3' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c28' => array( 'cols' => array( 1 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field5' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c25' => array( 'cols' => array( 1 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field4' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c22' => array( 'cols' => array( 1 ),
'rows' => array( 6 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field6' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c19' => array( 'cols' => array( 1 ),
'rows' => array( 7 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field7' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c16' => array( 'cols' => array( 1 ),
'rows' => array( 8 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field8' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c13' => array( 'cols' => array( 1 ),
'rows' => array( 9 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field9' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c10' => array( 'cols' => array( 1 ),
'rows' => array( 10 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field10' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c7' => array( 'cols' => array( 1 ),
'rows' => array( 11 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field12' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 12 ) ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false ),
'misc' => array( 'type' => 'view',
'breadcrumb' => false,
'nextPrev' => true ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'view',
'type' => 'view',
'layoutId' => 'nomenu',
'disabled' => 0,
'default' => 0,
'forms' => array( 'top' => array( 'modelId' => 'view-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'view_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'view-above-grid',
'grid' => array(  ),
'cells' => array(  ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'view-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'view_back_list',
'view_close' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'prev',
'next',
'hamburger' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'section' => '',
'cells' => array( array( 'cell' => 'c21',
'rowspan' => 12,
'colspan' => 1 ),
array( 'cell' => 'c30' ) ) ),
array( 'cells' => array( array( 'cell' => 'c',
'rowspan' => 1 ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c34' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c31' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c28' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c25' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c22' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c19' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c16' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c13' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c10' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c7' ) ) ) ),
'cells' => array( 'c' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field1' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'border' => array( array( 'side' => '',
'color' => '#0b85f3' ) ) ),
'c7' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field12' ),
'border' => array( array( 'side' => '',
'color' => '#0b85f3' ) ) ),
'c10' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field10' ),
'border' => array( array( 'side' => '',
'color' => '#0b85f3' ) ) ),
'c13' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field9' ),
'border' => array( array( 'side' => '',
'color' => '#0b85f3' ) ) ),
'c16' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field8' ),
'border' => array( array( 'side' => '',
'color' => '#0b85f3' ) ) ),
'c19' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field7' ),
'border' => array( array( 'side' => '',
'color' => '#0b85f3' ) ) ),
'c21' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field11' ) ),
'c22' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field6' ),
'border' => array( array( 'side' => '',
'color' => '#0b85f3' ) ) ),
'c25' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field4' ),
'border' => array( array( 'side' => '',
'color' => '#0b85f3' ) ) ),
'c28' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field5' ),
'border' => array( array( 'side' => '',
'color' => '#0b85f3' ) ) ),
'c31' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field3' ),
'border' => array( array( 'side' => '',
'color' => '#0b85f3' ) ) ),
'c34' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field2' ),
'border' => array( array( 'side' => '',
'color' => '#0b85f3' ) ) ),
'c30' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 2,
'inlineLabels' => false,
'separateLabels' => false ) ),
'items' => array( 'view_header' => array( 'type' => 'view_header' ),
'view_back_list' => array( 'type' => 'view_back_list' ),
'view_close' => array( 'type' => 'view_close' ),
'hamburger' => array( 'type' => 'hamburger',
'items' => array( 'view_pdf' ) ),
'integrated_edit_field1' => array( 'field' => 'asset_name',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field2' => array( 'field' => 'asset_model',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field3' => array( 'field' => 'asset_serial',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field4' => array( 'field' => 'manufactured_date',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field5' => array( 'field' => 'manufacturer',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field6' => array( 'field' => 'category_id',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field7' => array( 'field' => 'suplier_id',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field8' => array( 'field' => 'status_id',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field9' => array( 'field' => 'registration_date',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field10' => array( 'field' => 'purchased_date',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field11' => array( 'field' => 'image',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field12' => array( 'field' => 'taken',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field' => array( 'field' => 'asset_id',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'view_pdf' => array( 'type' => 'view_pdf',
'targetPages' => array(  ),
'splitModes' => array(  ),
'scopes' => array(  ) ),
'next' => array( 'type' => 'next' ),
'prev' => array( 'type' => 'prev' ) ),
'dbProps' => array(  ),
'version' => 4 );
		?>