<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'asset_name',
'asset_model',
'asset_serial',
'manufactured_date',
'manufacturer',
'category_id',
'suplier_id',
'status_id',
'registration_date',
'purchased_date',
'image',
'taken',
'asset_id' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'asset_name' => array( 'import_field1' ),
'asset_model' => array( 'import_field2' ),
'asset_serial' => array( 'import_field3' ),
'manufactured_date' => array( 'import_field4' ),
'manufacturer' => array( 'import_field5' ),
'category_id' => array( 'import_field6' ),
'suplier_id' => array( 'import_field7' ),
'status_id' => array( 'import_field8' ),
'registration_date' => array( 'import_field9' ),
'purchased_date' => array( 'import_field10' ),
'image' => array( 'import_field11' ),
'taken' => array( 'import_field12' ),
'asset_id' => array( 'import_field' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'import_header' ),
'grid' => array( 'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'import_header' => 'top',
'import_field1' => 'grid',
'import_field2' => 'grid',
'import_field3' => 'grid',
'import_field4' => 'grid',
'import_field5' => 'grid',
'import_field6' => 'grid',
'import_field7' => 'grid',
'import_field8' => 'grid',
'import_field9' => 'grid',
'import_field10' => 'grid',
'import_field11' => 'grid',
'import_field12' => 'grid',
'import_field' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'import_header' => array( 'import_header' ),
'import_field' => array( 'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'import',
'type' => 'import',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'import-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'import-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'import_header' => array( 'type' => 'import_header' ),
'import_field1' => array( 'field' => 'asset_name',
'type' => 'import_field' ),
'import_field2' => array( 'field' => 'asset_model',
'type' => 'import_field' ),
'import_field3' => array( 'field' => 'asset_serial',
'type' => 'import_field' ),
'import_field4' => array( 'field' => 'manufactured_date',
'type' => 'import_field' ),
'import_field5' => array( 'field' => 'manufacturer',
'type' => 'import_field' ),
'import_field6' => array( 'field' => 'category_id',
'type' => 'import_field' ),
'import_field7' => array( 'field' => 'suplier_id',
'type' => 'import_field' ),
'import_field8' => array( 'field' => 'status_id',
'type' => 'import_field' ),
'import_field9' => array( 'field' => 'registration_date',
'type' => 'import_field' ),
'import_field10' => array( 'field' => 'purchased_date',
'type' => 'import_field' ),
'import_field11' => array( 'field' => 'image',
'type' => 'import_field' ),
'import_field12' => array( 'field' => 'taken',
'type' => 'import_field' ),
'import_field' => array( 'field' => 'asset_id',
'type' => 'import_field' ) ),
'dbProps' => array(  ),
'version' => 4 );
		?>