<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'request_info_rq_id',
'request_info_employee_id',
'request_info_asset_id',
'request_info_model',
'request_info_quantity',
'request_info_approve_status_from_dept_manager',
'request_info_approve_status_from_asset_dept_manager',
'request_info_date',
'request_info_department',
'request_info_taked',
'request_info_seen' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'request_info_rq_id' => array( 'integrated_search_field' ),
'request_info_employee_id' => array( 'integrated_search_field1' ),
'request_info_asset_id' => array( 'integrated_search_field2' ),
'request_info_model' => array( 'integrated_search_field3' ),
'request_info_quantity' => array( 'integrated_search_field4' ),
'request_info_approve_status_from_dept_manager' => array( 'integrated_search_field5' ),
'request_info_approve_status_from_asset_dept_manager' => array( 'integrated_search_field6' ),
'request_info_date' => array( 'integrated_search_field7' ),
'request_info_department' => array( 'integrated_search_field8' ),
'request_info_taked' => array( 'integrated_search_field9' ),
'request_info_seen' => array( 'integrated_search_field10' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'top' => array( 'search_header' ),
'above-grid' => array(  ),
'below-grid' => array( 'search_search',
'search_reset',
'search_back_list',
'search_cancel' ),
'grid' => array( 'integrated_search_field',
'integrated_search_field1',
'integrated_search_field2',
'integrated_search_field3',
'integrated_search_field4',
'integrated_search_field5',
'integrated_search_field6',
'integrated_search_field7',
'integrated_search_field8',
'integrated_search_field9',
'integrated_search_field10' ) ),
'formXtTags' => array( 'above-grid' => array(  ) ),
'itemForms' => array( 'search_header' => 'top',
'search_search' => 'below-grid',
'search_reset' => 'below-grid',
'search_back_list' => 'below-grid',
'search_cancel' => 'below-grid',
'integrated_search_field' => 'grid',
'integrated_search_field1' => 'grid',
'integrated_search_field2' => 'grid',
'integrated_search_field3' => 'grid',
'integrated_search_field4' => 'grid',
'integrated_search_field5' => 'grid',
'integrated_search_field6' => 'grid',
'integrated_search_field7' => 'grid',
'integrated_search_field8' => 'grid',
'integrated_search_field9' => 'grid',
'integrated_search_field10' => 'grid' ),
'itemLocations' => array( 'integrated_search_field' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field1' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field2' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field3' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field4' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field5' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field6' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field7' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field8' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field9' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field10' => array( 'location' => 'grid',
'cellId' => 'c1' ) ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'search_header' => array( 'search_header' ),
'search_reset' => array( 'search_reset' ),
'search_back_list' => array( 'search_back_list' ),
'search_search' => array( 'search_search' ),
'search_cancel' => array( 'search_cancel' ),
'integrated_search_field' => array( 'integrated_search_field',
'integrated_search_field1',
'integrated_search_field2',
'integrated_search_field3',
'integrated_search_field4',
'integrated_search_field5',
'integrated_search_field6',
'integrated_search_field7',
'integrated_search_field8',
'integrated_search_field9',
'integrated_search_field10' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_search_field',
'integrated_search_field1',
'integrated_search_field2',
'integrated_search_field3',
'integrated_search_field4',
'integrated_search_field5',
'integrated_search_field6',
'integrated_search_field7',
'integrated_search_field8',
'integrated_search_field9',
'integrated_search_field10' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ) ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false ),
'misc' => array( 'type' => 'search',
'breadcrumb' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'search',
'type' => 'search',
'layoutId' => 'nomenu',
'disabled' => 0,
'default' => 0,
'forms' => array( 'top' => array( 'modelId' => 'search-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'search_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'search-above-grid',
'grid' => array(  ),
'cells' => array(  ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'search-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'search_search',
'search_reset',
'search_back_list',
'search_cancel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'simple-search',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_search_field',
'integrated_search_field1',
'integrated_search_field2',
'integrated_search_field3',
'integrated_search_field4',
'integrated_search_field5',
'integrated_search_field6',
'integrated_search_field7',
'integrated_search_field8',
'integrated_search_field9',
'integrated_search_field10' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'separateLabels' => false ) ),
'items' => array( 'search_header' => array( 'type' => 'search_header' ),
'search_reset' => array( 'type' => 'search_reset' ),
'search_back_list' => array( 'type' => 'search_back_list' ),
'search_search' => array( 'type' => 'search_search' ),
'search_cancel' => array( 'type' => 'search_cancel' ),
'integrated_search_field' => array( 'field' => 'request_info_rq_id',
'type' => 'integrated_search_field',
'orientation' => 0 ),
'integrated_search_field1' => array( 'field' => 'request_info_employee_id',
'type' => 'integrated_search_field',
'orientation' => 0 ),
'integrated_search_field2' => array( 'field' => 'request_info_asset_id',
'type' => 'integrated_search_field',
'orientation' => 0 ),
'integrated_search_field3' => array( 'field' => 'request_info_model',
'type' => 'integrated_search_field',
'orientation' => 0 ),
'integrated_search_field4' => array( 'field' => 'request_info_quantity',
'type' => 'integrated_search_field',
'orientation' => 0 ),
'integrated_search_field5' => array( 'field' => 'request_info_approve_status_from_dept_manager',
'type' => 'integrated_search_field',
'orientation' => 0 ),
'integrated_search_field6' => array( 'field' => 'request_info_approve_status_from_asset_dept_manager',
'type' => 'integrated_search_field',
'orientation' => 0 ),
'integrated_search_field7' => array( 'field' => 'request_info_date',
'type' => 'integrated_search_field',
'orientation' => 0 ),
'integrated_search_field8' => array( 'field' => 'request_info_department',
'type' => 'integrated_search_field',
'orientation' => 0 ),
'integrated_search_field9' => array( 'field' => 'request_info_taked',
'type' => 'integrated_search_field',
'orientation' => 0 ),
'integrated_search_field10' => array( 'field' => 'request_info_seen',
'type' => 'integrated_search_field',
'orientation' => 0 ) ),
'dbProps' => array(  ),
'version' => 4 );
		?>