<?php
			$optionsArray = array( 'totals' => array( 'id' => array( 'totalsType' => '' ),
'firstname' => array( 'totalsType' => '' ),
'lastname' => array( 'totalsType' => '' ),
'email' => array( 'totalsType' => '' ),
'phone' => array( 'totalsType' => '' ),
'hire_date' => array( 'totalsType' => '' ),
'salary' => array( 'totalsType' => '' ),
'house_no' => array( 'totalsType' => '' ),
'status' => array( 'totalsType' => '' ),
'job_id' => array( 'totalsType' => '' ),
'manager_id' => array( 'totalsType' => '' ),
'workunit_id' => array( 'totalsType' => '' ),
'photo' => array( 'totalsType' => '' ),
'department' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'id',
'firstname',
'lastname',
'email',
'phone',
'hire_date',
'salary',
'house_no',
'status',
'job_id',
'manager_id',
'workunit_id',
'photo',
'department' ),
'exportFields' => array( 'id',
'firstname',
'lastname',
'email',
'phone',
'hire_date',
'salary',
'house_no',
'status',
'job_id',
'manager_id',
'workunit_id',
'photo',
'department' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'id' => array( 'export_field' ),
'firstname' => array( 'export_field1' ),
'lastname' => array( 'export_field2' ),
'email' => array( 'export_field3' ),
'phone' => array( 'export_field4' ),
'hire_date' => array( 'export_field5' ),
'salary' => array( 'export_field6' ),
'house_no' => array( 'export_field7' ),
'status' => array( 'export_field8' ),
'job_id' => array( 'export_field9' ),
'manager_id' => array( 'export_field10' ),
'workunit_id' => array( 'export_field11' ),
'photo' => array( 'export_field12' ),
'department' => array( 'export_field13' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'export_header' ),
'grid' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13' ),
'footer' => array( 'export_export',
'export_cancel' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'export_header' => 'top',
'export_field' => 'grid',
'export_field1' => 'grid',
'export_field2' => 'grid',
'export_field3' => 'grid',
'export_field4' => 'grid',
'export_field5' => 'grid',
'export_field6' => 'grid',
'export_field7' => 'grid',
'export_field8' => 'grid',
'export_field9' => 'grid',
'export_field10' => 'grid',
'export_field11' => 'grid',
'export_field12' => 'grid',
'export_field13' => 'grid',
'export_export' => 'footer',
'export_cancel' => 'footer' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'export_header' => array( 'export_header' ),
'export_export' => array( 'export_export' ),
'export_cancel' => array( 'export_cancel' ),
'export_field' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'export' => array( 'format' => 2,
'selectFields' => false,
'delimiter' => ',',
'selectDelimiter' => false,
'exportFileTypes' => array( 'excel' => true,
'word' => true,
'csv' => true,
'xml' => false ) ) );
			$pageArray = array( 'id' => 'export',
'type' => 'export',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'export-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'export-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'export-footer',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'export_export',
'export_cancel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'export_header' => array( 'type' => 'export_header' ),
'export_export' => array( 'type' => 'export_export' ),
'export_cancel' => array( 'type' => 'export_cancel' ),
'export_field' => array( 'field' => 'id',
'type' => 'export_field' ),
'export_field1' => array( 'field' => 'firstname',
'type' => 'export_field' ),
'export_field2' => array( 'field' => 'lastname',
'type' => 'export_field' ),
'export_field3' => array( 'field' => 'email',
'type' => 'export_field' ),
'export_field4' => array( 'field' => 'phone',
'type' => 'export_field' ),
'export_field5' => array( 'field' => 'hire_date',
'type' => 'export_field' ),
'export_field6' => array( 'field' => 'salary',
'type' => 'export_field' ),
'export_field7' => array( 'field' => 'house_no',
'type' => 'export_field' ),
'export_field8' => array( 'field' => 'status',
'type' => 'export_field' ),
'export_field9' => array( 'field' => 'job_id',
'type' => 'export_field' ),
'export_field10' => array( 'field' => 'manager_id',
'type' => 'export_field' ),
'export_field11' => array( 'field' => 'workunit_id',
'type' => 'export_field' ),
'export_field12' => array( 'field' => 'photo',
'type' => 'export_field' ),
'export_field13' => array( 'field' => 'department',
'type' => 'export_field' ) ),
'dbProps' => array(  ),
'version' => 4,
'exportFormat' => 2,
'exportDelimiter' => ',',
'exportSelectDelimiter' => false,
'exportSelectFields' => false );
		?>