<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'id',
'as_name',
'model',
'serial',
'supplier_id',
'purchased_date',
'received_date',
'donor_id',
'receiver_id',
'manufactured_date',
'manufacturer',
'category_id',
'photo',
'price',
'receipt_no',
'type_id',
'seen',
'level' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'id' => array( 'import_field' ),
'as_name' => array( 'import_field1' ),
'model' => array( 'import_field2' ),
'serial' => array( 'import_field3' ),
'supplier_id' => array( 'import_field4' ),
'purchased_date' => array( 'import_field5' ),
'received_date' => array( 'import_field6' ),
'donor_id' => array( 'import_field7' ),
'receiver_id' => array( 'import_field8' ),
'manufactured_date' => array( 'import_field9' ),
'manufacturer' => array( 'import_field10' ),
'category_id' => array( 'import_field11' ),
'photo' => array( 'import_field12' ),
'price' => array( 'import_field13' ),
'receipt_no' => array( 'import_field14' ),
'type_id' => array( 'import_field15' ),
'seen' => array( 'import_field16' ),
'level' => array( 'import_field17' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'import_header' ),
'grid' => array( 'import_field',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field1',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'import_header' => 'top',
'import_field' => 'grid',
'import_field2' => 'grid',
'import_field3' => 'grid',
'import_field4' => 'grid',
'import_field5' => 'grid',
'import_field6' => 'grid',
'import_field7' => 'grid',
'import_field8' => 'grid',
'import_field9' => 'grid',
'import_field10' => 'grid',
'import_field11' => 'grid',
'import_field12' => 'grid',
'import_field1' => 'grid',
'import_field13' => 'grid',
'import_field14' => 'grid',
'import_field15' => 'grid',
'import_field16' => 'grid',
'import_field17' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'import_header' => array( 'import_header' ),
'import_field' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'import',
'type' => 'import',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'import-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'import-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_field',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field1',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'import_header' => array( 'type' => 'import_header' ),
'import_field' => array( 'field' => 'id',
'type' => 'import_field' ),
'import_field1' => array( 'field' => 'as_name',
'type' => 'import_field' ),
'import_field2' => array( 'field' => 'model',
'type' => 'import_field' ),
'import_field3' => array( 'field' => 'serial',
'type' => 'import_field' ),
'import_field4' => array( 'field' => 'supplier_id',
'type' => 'import_field' ),
'import_field5' => array( 'field' => 'purchased_date',
'type' => 'import_field' ),
'import_field6' => array( 'field' => 'received_date',
'type' => 'import_field' ),
'import_field7' => array( 'field' => 'donor_id',
'type' => 'import_field' ),
'import_field8' => array( 'field' => 'receiver_id',
'type' => 'import_field' ),
'import_field9' => array( 'field' => 'manufactured_date',
'type' => 'import_field' ),
'import_field10' => array( 'field' => 'manufacturer',
'type' => 'import_field' ),
'import_field11' => array( 'field' => 'category_id',
'type' => 'import_field' ),
'import_field12' => array( 'field' => 'photo',
'type' => 'import_field' ),
'import_field13' => array( 'field' => 'price',
'type' => 'import_field' ),
'import_field14' => array( 'field' => 'receipt_no',
'type' => 'import_field' ),
'import_field15' => array( 'field' => 'type_id',
'type' => 'import_field' ),
'import_field16' => array( 'field' => 'seen',
'type' => 'import_field' ),
'import_field17' => array( 'field' => 'level',
'type' => 'import_field' ) ),
'dbProps' => array(  ),
'version' => 4 );
		?>