<?php
			$optionsArray = array( 'totals' => array( 'id' => array( 'totalsType' => '' ),
'as_name' => array( 'totalsType' => '' ),
'model' => array( 'totalsType' => '' ),
'serial' => array( 'totalsType' => '' ),
'supplier_id' => array( 'totalsType' => '' ),
'purchased_date' => array( 'totalsType' => '' ),
'received_date' => array( 'totalsType' => '' ),
'donor_id' => array( 'totalsType' => '' ),
'receiver_id' => array( 'totalsType' => '' ),
'manufactured_date' => array( 'totalsType' => '' ),
'manufacturer' => array( 'totalsType' => '' ),
'category_id' => array( 'totalsType' => '' ),
'photo' => array( 'totalsType' => '' ),
'receipt_no' => array( 'totalsType' => '' ),
'seen' => array( 'totalsType' => '' ),
'type_id' => array( 'totalsType' => '' ),
'level' => array( 'totalsType' => '' ),
'price' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'id',
'as_name',
'model',
'serial',
'supplier_id',
'purchased_date',
'received_date',
'donor_id',
'receiver_id',
'manufactured_date',
'manufacturer',
'category_id',
'photo',
'price',
'receipt_no',
'type_id',
'seen',
'level' ),
'exportFields' => array( 'id',
'model',
'serial',
'supplier_id',
'purchased_date',
'received_date',
'donor_id',
'receiver_id',
'manufactured_date',
'manufacturer',
'category_id',
'photo',
'as_name',
'price',
'receipt_no',
'type_id',
'seen',
'level' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'id' => array( 'export_field' ),
'as_name' => array( 'export_field1' ),
'model' => array( 'export_field2' ),
'serial' => array( 'export_field3' ),
'supplier_id' => array( 'export_field4' ),
'purchased_date' => array( 'export_field5' ),
'received_date' => array( 'export_field6' ),
'donor_id' => array( 'export_field7' ),
'receiver_id' => array( 'export_field8' ),
'manufactured_date' => array( 'export_field9' ),
'manufacturer' => array( 'export_field10' ),
'category_id' => array( 'export_field11' ),
'photo' => array( 'export_field12' ),
'price' => array( 'export_field13' ),
'receipt_no' => array( 'export_field14' ),
'type_id' => array( 'export_field15' ),
'seen' => array( 'export_field16' ),
'level' => array( 'export_field17' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'export_header' ),
'grid' => array( 'export_field',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field1',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17' ),
'footer' => array( 'export_export',
'export_cancel' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'export_header' => 'top',
'export_field' => 'grid',
'export_field2' => 'grid',
'export_field3' => 'grid',
'export_field4' => 'grid',
'export_field5' => 'grid',
'export_field6' => 'grid',
'export_field7' => 'grid',
'export_field8' => 'grid',
'export_field9' => 'grid',
'export_field10' => 'grid',
'export_field11' => 'grid',
'export_field12' => 'grid',
'export_field1' => 'grid',
'export_field13' => 'grid',
'export_field14' => 'grid',
'export_field15' => 'grid',
'export_field16' => 'grid',
'export_field17' => 'grid',
'export_export' => 'footer',
'export_cancel' => 'footer' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'export_header' => array( 'export_header' ),
'export_export' => array( 'export_export' ),
'export_cancel' => array( 'export_cancel' ),
'export_field' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'export' => array( 'format' => 2,
'selectFields' => false,
'delimiter' => ',',
'selectDelimiter' => false,
'exportFileTypes' => array( 'excel' => true,
'word' => true,
'csv' => true,
'xml' => false ) ) );
			$pageArray = array( 'id' => 'export',
'type' => 'export',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'export-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'export-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_field',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field1',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'export-footer',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'export_export',
'export_cancel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'export_header' => array( 'type' => 'export_header' ),
'export_export' => array( 'type' => 'export_export' ),
'export_cancel' => array( 'type' => 'export_cancel' ),
'export_field' => array( 'field' => 'id',
'type' => 'export_field' ),
'export_field1' => array( 'field' => 'as_name',
'type' => 'export_field' ),
'export_field2' => array( 'field' => 'model',
'type' => 'export_field' ),
'export_field3' => array( 'field' => 'serial',
'type' => 'export_field' ),
'export_field4' => array( 'field' => 'supplier_id',
'type' => 'export_field' ),
'export_field5' => array( 'field' => 'purchased_date',
'type' => 'export_field' ),
'export_field6' => array( 'field' => 'received_date',
'type' => 'export_field' ),
'export_field7' => array( 'field' => 'donor_id',
'type' => 'export_field' ),
'export_field8' => array( 'field' => 'receiver_id',
'type' => 'export_field' ),
'export_field9' => array( 'field' => 'manufactured_date',
'type' => 'export_field' ),
'export_field10' => array( 'field' => 'manufacturer',
'type' => 'export_field' ),
'export_field11' => array( 'field' => 'category_id',
'type' => 'export_field' ),
'export_field12' => array( 'field' => 'photo',
'type' => 'export_field' ),
'export_field13' => array( 'field' => 'price',
'type' => 'export_field' ),
'export_field14' => array( 'field' => 'receipt_no',
'type' => 'export_field' ),
'export_field15' => array( 'field' => 'type_id',
'type' => 'export_field' ),
'export_field16' => array( 'field' => 'seen',
'type' => 'export_field' ),
'export_field17' => array( 'field' => 'level',
'type' => 'export_field' ) ),
'dbProps' => array(  ),
'version' => 4,
'exportFormat' => 2,
'exportDelimiter' => ',',
'exportSelectDelimiter' => false,
'exportSelectFields' => false );
		?>